tag: ""
random_seed: 42

##############
# Dataloader #
##############
dataloader:
  # shakespeare, lexicap
  dataset: "shakespeare"
  num_workers: 0

#########
# Model #
#########
model:
  input_sequence_length: 64
  output_sequence_length: 8
  embedding_dim: 256
  expansion_factor: 1
  num_blocks: 4

###########
# Trainer #
###########
trainer:
  # gpu, cpu
  device: "gpu"
  start_update_step: 0
  num_update_steps: 200000
  batch_size: 64
  weight_decay: 0
  initial_learning_rate: 1.0e-6
  max_learning_rate: 0.01
  gradient_clipping:
    is_activated: true 
    max_norm: 1.0

load_model:
  is_activated: false 
  model_name: "lexicap"
  model_path: -1

########
# Data #
########
data:
  n_classes: Null
  input_shape: Null

###########
# Summary #
###########
summary:
  save_train_stats:
    every_n_updates: 100
  save_test_stats:
    every_n_updates: -1
  save_model:
    every_n_updates: 5000
  add_position_embeddings:
    every_n_updates: 2000
  add_token_embeddings:
    every_n_updates: 2000
  add_linear_weights:
    every_n_updates: 2000
  add_graph: false

###############
# Directories #
###############
dirs:
  data: "data"
  runs: "runs"
  weights: "weights"