tag: "03"
random_seed: 44

##############
# Dataloader #
##############
# shakespeare, lexicap
dataloader:
  dataset: "lexicap"
  num_workers: 2

#########
# Model #
#########
model:
  sequence_length: 128
  embedding_dims: 128
  token_dims: 1024
  channel_dims: 1024
  expansion_factor: 4  # instead of token_dims / channel_dims
  num_blocks: 8
  dropout_probability: 0.3

###########
# Trainer #
###########
trainer:
  device: "gpu"   # gpu, cpu
  start_update_step: 0
  num_update_steps: 20000
  batch_size: 64
  weight_decay: 0
  initial_learning_rate: 1.0e-6
  max_learning_rate: 0.001
  gradient_clipping:
    is_activated: true 
    max_norm: 1.0

load_model:
  is_activated: false 
  model_name: "lexicap_03"
  model_path: -1

########
# Data #
########
data:
  n_classes: Null
  input_shape: Null

###########
# Summary #
###########
summary:
  save_train_stats:
    every_n_updates: 100
  save_test_stats:
    every_n_updates: -1
  save_model:
    every_n_updates: 5000
  add_position_embeddings:
    every_n_updates: 1000
  add_token_embeddings:
    every_n_updates: 1000
  add_linear_weights:
    every_n_updates: 1000
  add_graph: false

###############
# Directories #
###############
dirs:  # TODO: dirs -> dir
  data: "data"
  runs: "runs"
  weights: "weights"