tag: "32"
random_seed: 42

##############
# Dataloader #
##############
dataloader:
  dataset: "lexicap"
  num_workers: 0

#########
# Model #
#########
model:
  # type [cnn, mlp]
  type: "cnn"
  num_blocks: 4
  input_sequence_length: 128
  output_sequence_length: 1
  embedding_dim: 32
  expansion_factor: 1  # only for MLP-Mixer
  kernel_size: 5       # only for ConvMixer

###########
# Trainer #
###########
trainer:
  # gpu, cpu
  device: "gpu"
  num_update_steps: 10000000
  batch_size: 64
  learning_rate: 5.0e-4
  weight_decay: 0
  gradient_clipping:
    is_activated: false
    max_norm: 1.0

load_model:
  is_activated: false 
  model_name: "lexicap_256"
  model_path: -1

########
# Data #
########
data:
  n_classes: Null
  input_shape: Null

###########
# Summary #
###########
summary:
  save_train_stats:
    every_n_updates: 100
  save_test_stats:
    every_n_updates: -1
  save_model:
    every_n_updates: 10000
  add_position_embeddings:
    every_n_updates: 10000
  add_token_embeddings:
    every_n_updates: 10000
  add_linear_weights:
    every_n_updates: 10000
  add_graph: false

###############
# Directories #
###############
dirs:
  data: "data"
  runs: "runs"
  weights: "weights"
