tag: ""
random_seed: 42

##############
# Dataloader #
##############
# shakespeare, lexicap
dataloader:
  dataset: "lexicap"
  num_workers: 2

#########
# Model #
#########
model:
  max_sequence_length: 1024 # or just sequence_length as it is static for mixers
  num_dims: 256  # dim, embedding_dims
  token_dims: 1024
  channel_dims: 1024
  num_blocks: 16
  # Available encoding schemes: ones, zeros, random_normal
  position_embedding:
    is_activated: true
    is_trainable: true
    encoding: "random_normal"
  mixer_block:
    # dim: 128
    dropout_prob: 0.05
    use_bias: True
  mlp_block:
    # hidden_dim: 256
    dropout_prob: 0.05
    use_bias: True
  classifier: # head
    use_bias: True

###########
# Trainer #
###########
trainer:
  device: "gpu"   # gpu, cpu
  num_update_steps: 100000
  batch_size: 4
  weight_decay: 0
  initial_learning_rate: 1.0e-6
  max_learning_rate: 0.001
  grad_norm_clip: 1.0  # TODO: Use version below.
  gradient_clipping:
    is_activated: true
    max_norm: 1.0

load_model:
  is_activated: false 
  model_name: "ckpt"
  model_path: -1

########
# Data #
########
data:
  n_classes: Null
  input_shape: Null

###########
# Summary #
###########
summary:
  save_train_stats:
    every_n_updates: 100
  save_test_stats:
    every_n_updates: -1
  save_model:
    every_n_updates: 5000
  add_patch_embeddings:
    every_n_updates: -1 
  add_position_embeddings:
    every_n_updates: 5000
  add_token_embeddings:
    every_n_updates: 5000
  add_mask_weights:
    every_n_updates: 5000
  add_params_hist:
    every_n_updates: -1
  add_graph: false
  add_sample_batch: false
  add_hparams: false

###############
# Directories #
###############
dirs:  # TODO: dirs -> dir
  data: "data"
  runs: "runs"
  weights: "weights"