########
# NetLab
########

tag: Null
random_seed: 0

##############
# Dataloader #
##############
dataloader:
  dataset: "lexicap"
  num_workers: 2

########
# Data #
########
data:
  num_classes: Null
  input_shape: Null

#########
# Model #
#########

chatmixer:
  n_channels_hidden: 16
  n_channels_out: 8
  n_blocks: 4

###########
# Trainer #
###########

trainer:
  device: "gpu"   # gpu, cpu
  n_epochs: 10
  learning_rate: 3.0e-4
  weight_decay: 0
  lr_step_size: 2
  lr_gamma: 0.5
  batch_size: 512
  grad_norm_clip: 1.0

###########
# Summary #
###########

summary:
  add_graph: false
  add_sample_batch: false
  add_hparams: false
  add_train_stats_every_n_epochs: 1
  add_test_stats_every_n_epochs: 10
  add_weights_every_n_epochs: false
  add_params_hist_every_n_epochs: false
  add_model_every_n_epochs: false

checkpoints:
  load_model: 0
  model_path: 0

###############
# Directories #
###############

dirs:
  data: "data"
  runs: "runs"
  weights: "weights"